function defaults = getDefaultParameters(isBinaryFeature, isRadiusSearch)
%getDefaultParameters Get the default parameter values 

%   Copyright 2020 The MathWorks, Inc.

%#codegen

if isBinaryFeature
    thresh = 10.0;
else
    thresh = 1.0;
end

if isRadiusSearch
    defaults = struct(...
        'Metric', 'ssd', ...
        'MatchThreshold',  thresh, ...
        'MaxRatio', 0.6, ...
        'Unique', false);
else
    defaults = struct(...
        'Metric', 'ssd', ...
        'MatchThreshold',  thresh, ...
        'Method', 'exhaustive',...
        'MaxRatio', 0.6,...
        'Prenormalized', false,...
        'Unique', false);
end